### PR TITLE
Depend on libnsl

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is an attempt to fix the `libnsl` dependency issue reported and discussed at https://github.com/conda-forge/rasterio-feedstock/issues/220 and https://github.com/conda-forge/cmake-feedstock/issues/69. It needs https://github.com/conda-forge/staged-recipes/pull/16278 to be merged first.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin, please rerender

**Comment by frol** [comment]
@izahn Please, do `git commit --amend` + `git push --force-with-lease` to re-run CI

**Comment by izahn** [comment]
@conda-forge-admin please restart current

**Comment by izahn** [comment]
@conda-forge-admin please restart ci

**Comment by mbargull** [comment]
I believe the it was just a hunch at https://github.com/conda-forge/cmake-feedstock/issues/69 that libuv was the one pulling in libnsl because it seemingly was the only noticeable difference in the Anaconda/conda-forge builds.
I don't know if there is a better/efficient way to find out which libraries link to libnsl, but you could run something like
```
find "${CONDA_PREFIX}" -name '*.so*' -exec sh -c 'readelf -d {} 2> /dev/null | grep NEEDED | grep -q libnsl' \; -print
```
to see which files actually do.

**Review by frol — APPROVED** [review]

**Comment by mbargull** [comment]
I'd suggest to close this PR and rather inspect which package really links to libnsl.

**Comment by izahn** [comment]
I didn't dig into it very hard, I just saw that https://github.com/conda-forge/cmake-feedstock/issues/69 suggested that `libuv` needed `libnsl` and that the Arch Linux `libuv` package also depends on `libnsl`. Feel free to close if you are confident that it is not needed.

**Comment by hmaarrfk** [comment]
I think it is easier to migrate the dependency.

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1985

**Comment by mbargull** [comment]
> I think it is easier to migrate the dependency.
> 
> [conda-forge/conda-forge-pinning-feedstock#1985](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1985)

It definitely makes sense to build libnsl for the other platforms, yes! But that is unrelated to the question whether libuv should depend on libnsl or not.

> I didn't dig into it very hard, I just saw that [conda-forge/cmake-feedstock#69](https://github.com/conda-forge/cmake-feedstock/issues/69) suggested that `libuv` needed `libnsl` and that the Arch Linux `libuv` package also depends on `libnsl`. Feel free to close if you are confident that it is not needed.

Apparently upstream also checks for libnsl, but thankfully doesn't link to it if not needed, see https://github.com/libuv/libuv/commit/b4fe4f6ad91d380c6af2b4ab2a1c624e58947608 .
What does not make sense to me is that they check `AC_SEARCH_LIBS([gethostbyname], [nsl]`, because `gethostbyname` comes from `netdb.h` not libnsl, see https://man7.org/linux/man-pages/man3/gethostbyname.3.html . Maybe there are other (read: non-Linux/glibc-based) platforms where that isn't the case?
Anyway, libuv does not need/link to libnsl on Linux, so it'd be wrong to add it here AFAICT.

**Comment by mbargull** [comment]
> Maybe there are other (read: non-Linux/glibc-based) platforms where that isn't the case?

Looks like SunOS/Solaris would be such platforms
https://www.unix.com/man-page/sunos/3lib/libnsl/

**Pull request closed without merging**
